import React from 'react';

const images = require.context("../../images/flags", true);
const FLAG_MAP = [
    {name: "United Arab Emirates", code: "ae"},
    {name: "Afghanistan", code: "af"},
    {name: "Albania", code: "al"},
    {name: "Angola", code: "ao"},
    {name: "Argentina", code: "ar"},
    {name: "Austria", code: "at"},
    {name: "Australia", code: "au"},
    {name: "Bosnia Herzegovina", code: "ba"},
    {name: "Belgium", code: "be"},
    {name: "Bulgaria", code: "bg"},
    {name: "Bolivia", code: "bo"},
    {name: "Brazil", code: "br"},
    {name: "Bhutan", code: "bt"},
    {name: "Belarus", code: "by"},
    {name: "Canada", code: "ca"},
    {name: "Central African Rep.", code: "cf"},
    {name: "Switzerland", code: "ch"},
    {name: "Côte d'Ivoire", code: "ci"},
    {name: "Chile", code: "cl"},
    {name: "Cameroon", code: "cm"},
    {name: "China", code: "cn"},
    {name: "Colombia", code: "co"},
    {name: "Costa Rica", code: "cr"},
    {name: "Cuba", code: "cu"},
    {name: "Cyprus", code: "cy"},
    {name: "Czech Republic", code: "cz"},
    {name: "Germany", code: "de"},
    {name: "Denmark", code: "dk"},
    {name: "Dominican Republic", code: "do"},
    {name: "Algeria", code: "dz"},
    {name: "Estonia", code: "ee"},
    {name: "Egypt", code: "eg"},
    {name: "Spain", code: "es"},
    {name: "Ethiopia", code: "et"},
    {name: "Finland", code: "fi"},
    {name: "France", code: "fr"},
    {name: "United Kingdom", code: "gb"},
    {name: "Georgia", code: "ge"},
    {name: "Ghana", code: "gh"},
    {name: "Greece", code: "gr"},
    {name: "Guatemala", code: "gt"},
    {name: "Honduras", code: "hn"},
    {name: "Croatia", code: "hr"},
    {name: "Hungary", code: "hu"},
    {name: "Indonesia", code: "id"},
    {name: "Ireland", code: "ie"},
    {name: "Israel", code: "il"},
    {name: "India", code: "in"},
    {name: "Iraq", code: "iq"},
    {name: "Iran", code: "ir"},
    {name: "Iceland", code: "is"},
    {name: "Italy", code: "it"},
    {name: "Jamaica", code: "jm"},
    {name: "Japan", code: "jp"},
    {name: "Kenya", code: "ke"},
    {name: "North Korea", code: "kp"},
    {name: "South Korea", code: "kr"},
    {name: "Kazakhstan", code: "kz"},
    {name: "Lebanon", code: "lb"},
    {name: "Sri Lanka", code: "lk"},
    {name: "Lithuania", code: "lt"},
    {name: "Latvia", code: "lv"},
    {name: "Morocco", code: "ma"},
    {name: "North Macedonia", code: "mk"},
    {name: "Mali", code: "ml"},
    {name: "Mongolia", code: "mn"},
    {name: "Malta", code: "mt"},
    {name: "Mexico", code: "mx"},
    {name: "Malaysia", code: "my"},
    {name: "Mozambique", code: "mz"},
    {name: "Nigeria", code: "ng"},
    {name: "Nicaragua", code: "ni"},
    {name: "Netherlands", code: "nl"},
    {name: "Norway", code: "no"},
    {name: "Nepal", code: "np"},
    {name: "Panama", code: "pa"},
    {name: "Peru", code: "pe"},
    {name: "Philippines", code: "ph"},
    {name: "Pakistan", code: "pk"},
    {name: "Poland", code: "pl"},
    {name: "Portugal", code: "pt"},
    {name: "Qatar", code: "qa"},
    {name: "Romania", code: "ro"},
    {name: "Russia", code: "ru"},
    {name: "Saudi Arabia", code: "sa"},
    {name: "Sweden", code: "se"},
    {name: "Senegal", code: "sn"},
    {name: "Somalia", code: "so"},
    {name: "Thailand", code: "th"},
    {name: "Turkmenistan", code: "tm"},
    {name: "Turkey", code: "tr"},
    {name: "Ukraine", code: "ua"},
    {name: "Uganda", code: "ug"},
    {name: "USA", code: "us"},
    {name: "Uruguay", code: "uy"},
    {name: "Vatican", code: "va"},
    {name: "Venezuela", code: "ve"},
    {name: "Vietnam", code: "vn"},
    {name: "South Africa", code: "za"},
    {name: "Zimbabwe", code: "zw"},
];

export const Flag = (props) => (
    <span role="img" onClick={props.clickHandler}>
        <img className={props.className}
            src={images('./' + FLAG_MAP[props.num].code + '.png').default} />
    </span>
);

export const Label = (props) => (
    <span role="img" className={props.className} onClick={props.clickHandler}>
        {FLAG_MAP[props.num].name}
    </span>
);