import React from 'react';

const audio = require.context("../../audio", true);

/* eslint no-eval: 0 */
// eslint-disable-next-line no-unused-vars
const KIDS_MAP_ES = [
    {text: "Un ratón", question: "¿Dónde está el ratón?", hex: 0x1F401, fileName: "mouse"},
    {text: "Una vaca", question: "¿Dónde está la vaca?", hex: 0x1F404, fileName: "cow"},
    {text: "Un conejo", question: "¿Dónde está el conejo?", hex: 0x1F407, fileName: "rabbit"},
    {text: "Un gato", question: "¿Dónde está el gato?", hex: 0x1F408, fileName: "cat"},
    {text: "Un cocodrilo", question: "¿Dónde está el cocodrilo?", hex: 0x1F40A, fileName: "crocodile"},
    {text: "Una ballena", question: "¿Dónde está la ballena?", hex: 0X1F40B, fileName: "whale"},
    {text: "Un caracol", question: "¿Dónde está el caracol?", hex: 0x1F40C, fileName: "snail"},
    {text: "Un elefante", question: "¿Dónde está el elefante?", hex: 0x1F418, fileName: "elephant"},
    {text: "Un pez", question: "¿Dónde está el pez?", hex: 0x1F41F, fileName: "fish"},
    {text: "Un koala", question: "¿Dónde está el koala", hex: 0x1F428, fileName: "koala"},
    {text: "Un caballo", question: "¿Dónde está el caballo?", hex: 0x1F434, fileName: "horse"},
    {text: "Un mono", question: "¿Dónde está el mono?", hex: 0x1F435, fileName: "monkey"},    
    {text: "Un perro", question: "¿Dónde está un perro?", hex: 0x1F436, fileName: "dog"},
    {text: "Un cerdo", question: "¿Dónde está el cerdo?", hex: 0x1F437, fileName: "pig"}, 
    {text: "Una rana", question: "¿Dónde está la rana?", hex: 0x1F438, fileName: "frog"},
    {text: "Un oso panda", question: "¿Dónde está el oso panda?", hex: 0x1F43C, fileName: "panda"},
    {text: "Un balón", question: "¿Dónde está el balón?", hex: 0x26BD, fileName: "ball"},
    {text: "Una montaña", question: "¿Dónde está la montaña?", hex: 0x26F0, fileName: "mountain"},
    {text: "Una fuente", question: "¿Dónde está la fuente?", hex: 0x26F2, fileName: "fountain"},
    {text: "Un arco iris", question: "¿Dónde está el arco iris?", hex: 0x1F308, fileName: "rainbow"},
    {text: "Un árbol", question: "¿Dónde está el árbol?", hex: 0x1F332, fileName: "tree"},
    {text: "Una flor", question: "¿Dónde está la flor?", hex: 0x1F338, fileName: "flower"},
    {text: "Un tomate", question: "¿Dónde está el tomate?", hex: 0x1F345, fileName: "tomato"},
    {text: "Una berenjena", question: "¿Dónde está la berenjena?", hex: 0x1F346, fileName: "aubergine"},
    {text: "Unas uvas", question: "¿Dónde están las uvas?", hex: 0x1F347, fileName: "grapes"},
    {text: "Una sandía", question: "¿Dónde está la sandía?", hex: 0x1F349, fileName: "watermelon"},
    {text: "Una naranja", question: "¿Dónde está la naranja?", hex: 0x1F34A, fileName: "orange"},
    {text: "Un limón", question: "¿Dónde está el limón?", hex: 0x1F34B, fileName: "lemon"},
    {text: "Un plátano", question: "¿Dónde está el plátano?", hex: 0x1F34C, fileName: "banana"},
    {text: "Una manzana", question: "¿Dónde está la manzana?", hex: 0x1F34F, fileName: "apple"},
    {text: "Una pera", question: "¿Dónde está la pera?", hex: 0x1F350, fileName: "pear"},
    {text: "Unas cerezas", question: "¿Dónde están las cerezas?", hex: 0x1F352, fileName: "cherries"},
    {text: "Una fresa", question: "¿Dónde está la fresa?", hex: 0x1F353, fileName: "strawberry"},
    {text: "Una pizza", question: "¿Dónde está la pizza?", hex: 0x1F355, fileName: "pizza"},
    {text: "Un helado", question: "¿Dónde está el helado?", hex: 0x1F366, fileName: "icecream"},
    {text: "Un regalo", question: "¿Dónde está el regalo?", hex: 0x1F381, fileName: "present"},
    {text: "Una tarta", question: "¿Dónde está la tarta?", hex: 0x1F382, fileName: "cake"},
    {text: "Una calabaza", question: "¿Dónde está la calabaza?", hex: 0x1F383, fileName: "pumpkin"},
    {text: "Un globo", question: "¿Dónde está el globo?", hex: 0x1F388, fileName: "balloon"},
    {text: "Un circo", question: "¿Dónde está el circo?", hex: 0x1F3AA, fileName: "circus"},
    {text: "Un piano", question: "¿Dónde está el piano?", hex: 0x1F3B9, fileName: "piano"},
    {text: "Un violín", question: "¿Dónde está el violín?", hex: 0x1F3BB, fileName: "violin"},
    {text: "Una playa", question: "¿Dónde está la playa?", hex: 0x1F3DD, fileName: "beach"},
    {text: "Una casa", question: "¿Dónde está la casa?", hex: 0x1F3E0, fileName: "house"},
    {text: "Una serpiente", question: "¿Dónde está la serpiente?", hex: 0x1F40D, fileName: "snake"},
    {text: "Una oveja", question: "¿Dónde está la oveja?", hex: 0x1F411, fileName: "sheep"},
    {text: "Una gallina", question: "¿Dónde está la gallina?", hex: 0x1F413, fileName: "hen"},
    {text: "Un pulpo", question: "¿Dónde está el pulpo?", hex: 0x1F419, fileName: "octopus"},
    {text: "Una hormiga", question: "¿Dónde está la hormiga?", hex: 0x1F41C, fileName: "ant"},
    {text: "Una abeja", question: "¿Dónde está la abeja?", hex: 0x1F41D, fileName: "bee"},
    {text: "Una tortuga", question: "¿Dónde está la tortuga?", hex: 0x1F422, fileName: "turtle"},
    {text: "Un pollito", question: "¿Dónde está el pollito?", hex: 0x1F425, fileName: "chick"},
    {text: "Un camello", question: "¿Dónde está el camello?", hex: 0x1F42A, fileName: "camel"},
    {text: "Un delfín", question: "¿Dónde está el delfín?", hex: 0x1F42C, fileName: "dolphin"},
    {text: "Un tigre", question: "¿Dónde está el tigre?", hex: 0x1F42F, fileName: "tiger"},
    {text: "Un oso", question: "¿Dónde está el oso?", hex: 0x1F43B, fileName: "bear"},
    {text: "Una ardilla", question: "¿Dónde está la ardilla?", hex: 0x1F43F, fileName: "squirrel"},
    {text: "Un ojo", question: "¿Dónde está el ojo?", hex: 0x1F441, fileName: "eye"},
    {text: "Una oreja", question: "¿Dónde está la oreja?", hex: 0x1F442, fileName: "ear"},
    {text: "Una nariz", question: "¿Dónde está la nariz?", hex: 0x1F443, fileName: "nose"},
    {text: "Una boca", question: "¿Dónde está la boca?", hex: 0x1F444, fileName: "mouth"},
    {text: "Una mano", question: "¿Dónde está la mano?", hex: 0x1F44B, fileName: "hand"},
    {text: "Unas gafas", question: "¿Dónde están las gafas?", hex: 0x1F453, fileName: "glasses"},
    {text: "Una camiseta", question: "¿Dónde está la camiseta?", hex: 0x1F455, fileName: "tshirt"},
    {text: "Unos pantalones", question: "¿Dónde están los pantalones?", hex: 0x1F456, fileName: "trousers"},
    {text: "Un vestido", question: "¿Dónde está el vestido?", hex: 0x1F457, fileName: "dress"},
    {text: "Un zapato", question: "¿Dónde está el zapato?", hex: 0x1F45E, fileName: "shoe"},
    {text: "Un niño", question: "¿Dónde está el niño?", hex: 0x1F466, fileName: "boy"},
    {text: "Una niña", question: "¿Dónde está la niña?", hex: 0x1F467, fileName: "girl"},
    {text: "Un libro", question: "¿Dónde está el libro?", hex: 0x1F4D7, fileName: "book"},
    {text: "Un teléfono", question: "¿Dónde está el teléfono?", hex: 0x1F4F1, fileName: "phone"},
    {text: "El fuego", question: "¿Dónde está el fuego?", hex: 0x1F525, fileName: "fire"},
    {text: "Un cuchillo", question: "¿Dónde está el cuchillo?", hex: 0x1F52A, fileName: "knife"},
    {text: "Una araña", question: "¿Dónde está la araña?", hex: 0x1F577, fileName: "spider"},
    {text: "Una televisión", question: "¿Dónde está la televisión?", hex: 0x1F5A5, fileName: "tv"},
    {text: "Un helicóptero", question: "¿Dónde está el helicóptero?", hex: 0x1F681, fileName: "helicopter"},
    {text: "Un tren", question: "¿Dónde está el tren?", hex: 0x1F686, fileName: "train"},
    {text: "Un autobús", question: "¿Dónde está el autobús?", hex: 0x1F68C, fileName: "bus"},
    {text: "Una ambulancia", question: "¿Dónde está la ambulancia?", hex: 0x1F691, fileName: "ambulance"},
    {text: "Un taxi", question: "¿Dónde está el taxi?", hex: 0x1F695, fileName: "taxi"},
    {text: "Un coche", question: "¿Dónde está el coche?", hex: 0x1F697, fileName: "car"},
    {text: "Un camión", question: "¿Dónde está el camión?", hex: 0x1F69B, fileName: "truck"},
    {text: "Un tractor", question: "¿Dónde está el tractor?", hex: 0x1F69C, fileName: "tractor"},
    {text: "Una ensalada", question: "¿Dónde está la ensalada?", hex: 0x1F957, fileName: "salad"},
    {text: "Un huevo", question: "¿Dónde está el huevo?", hex: 0x1F95A, fileName: "egg"},
    {text: "Un kiwi", question: "¿Dónde está el kiwi?", hex: 0x1F95D, fileName: "kiwi"},
    {text: "Un brócoli", question: "¿Dónde está el brócoli?", hex: 0x1F966, fileName: "broccoli"},
    {text: "Un cangrejo", question: "¿Dónde está el cangrejo?", hex: 0x1F980, fileName: "crab"},
    {text: "Un león", question: "¿Dónde está el león?", hex: 0x1F981, fileName: "lion"},
    {text: "Un pato", question: "¿Dónde está el pato?", hex: 0x1F986, fileName: "duck"},
    {text: "Un murciélago", question: "¿Dónde está el murciélago?", hex: 0x1F987, fileName: "bat"},
    {text: "Un tiburón", question: "¿Dónde está el tiburón?", hex: 0x1F988, fileName: "shark"},
    {text: "Un barco", question: "¿Dónde está el barco?", hex: 0x1F6A2, fileName: "boat"},
    {text: "Una bicicleta", question: "¿Dónde está la bicicleta?", hex: 0x1F6B2, fileName: "bike"},
    {text: "Una cama", question: "¿Dónde está la cama?", hex: 0x1F6CC, fileName: "bed"},
    {text: "Un avión", question: "¿Dónde está el avión?", hex: 0x1F6E9, fileName: "plane"},
    {text: "Una moto", question: "¿Dónde está la moto?", hex: 0x1F6F5, fileName: "motorbike"},
    {text: "Un tambor", question: "¿Dónde está el tambor?", hex: 0x1F941, fileName: "drums"},
    {text: "Un aguacate", question: "¿Dónde está el aguacate?", hex: 0x1F951, fileName: "avocado"},
    {text: "Un pepino", question: "¿Dónde está el pepino?", hex: 0x1F952, fileName: "cucumber"},
    {text: "Una zanahoria", question: "¿Dónde está la zanahoria?", hex: 0x1F955, fileName: "carrot"},
    {text: "Un corazón", question: "¿Dónde está el corazón?", hex: 0x1F9E1, fileName: "heart"},
    {text: "Un búho", question: "¿Dónde está el búho?", hex: 0x1F989, fileName: "owl"},
    {text: "Una mariposa", question: "¿Dónde está la mariposa?", hex: 0x1F98B, fileName: "butterfly"},
    {text: "Un gorila", question: "¿Dónde está el gorila?", hex: 0x1F98D, fileName: "gorilla"},
    {text: "Una jirafa", question: "¿Dónde está la jirafa?", hex: 0x1F992, fileName: "giraffe"},
    {text: "Una cebra", question: "¿Dónde está la cebra?", hex: 0x1F993, fileName: "zebra"},
    {text: "Un dinosaurio", question: "¿Dónde está el dinosaurio?", hex: 0x1F996, fileName: "dinosaur"},
    {text: "El sol", question: "¿Dónde está el sol?", hex: 0x1F31E, fileName: "sun"},
    {text: "La luna", question: "¿Dónde está la luna?", hex: 0x1F31B, fileName: "moon"},
    {text: "Una estrella", question: "¿Dónde está la estrella?", hex: 0x1F31F, fileName: "star"},
    {text: "La lluvia", question: "¿Dónde está la lluvia?", hex: 0x1F327, fileName: "rain"}
];

// eslint-disable-next-line no-unused-vars
const KIDS_MAP_EN = [
    {text: "A mouse", question: "Where is the mouse?", hex: 0x1F401, fileName: "mouse"},
    {text: "A cow", question: "Where is the cow?", hex: 0x1F404, fileName: "cow"},
    {text: "A rabbit", question: "Where is the rabbit", hex: 0x1F407, fileName: "rabbit"},
    {text: "A cat", question: "Where is the cat?", hex: 0x1F408, fileName: "cat"},
    {text: "A crocodile", question: "Where is the crocodile?", hex: 0x1F40A, fileName: "crocodile"},
    {text: "A whale", question: "Where is the whale?", hex: 0X1F40B, fileName: "whale"},
    {text: "A snail", question: "Where is the snail?", hex: 0x1F40C, fileName: "snail"},
    {text: "An elephant", question: "Where is the elephant?", hex: 0x1F418, fileName: "elephant"},
    {text: "A fish", question: "Where is the fish?", hex: 0x1F41F, fileName: "fish"},
    {text: "A koala", question: "Where is the koala?", hex: 0x1F428, fileName: "koala"},
    {text: "A horse", question: "Where is the horse?", hex: 0x1F434, fileName: "horse"},
    {text: "A monkey", question: "Where is the monkey?", hex: 0x1F435, fileName: "monkey"},    
    {text: "A dog", question: "Where is the dog?", hex: 0x1F436, fileName: "dog"},
    {text: "A pig", question: "Where is the pig?", hex: 0x1F437, fileName: "pig"}, 
    {text: "A frog", question: "Where is the frog?", hex: 0x1F438, fileName: "frog"},
    {text: "A panda", question: "Where is the panda?", hex: 0x1F43C, fileName: "panda"},
    {text: "A ball", question: "Where is the ball?", hex: 0x26BD, fileName: "ball"},
    {text: "A mountain", question: "Where is the mountain?", hex: 0x26F0, fileName: "mountain"},
    {text: "A fountain", question: "Where is the fountain?", hex: 0x26F2, fileName: "fountain"},
    {text: "The rainbow", question: "Where is the rainbow?", hex: 0x1F308, fileName: "rainbow"},
    {text: "A tree", question: "Where is the tree?", hex: 0x1F332, fileName: "tree"},
    {text: "A flower", question: "Where is the flower?", hex: 0x1F338, fileName: "flower"},
    {text: "A tomato", question: "Where is the tomato?", hex: 0x1F345, fileName: "tomato"},
    {text: "An aubergine", question: "Where is the aubergine?", hex: 0x1F346, fileName: "aubergine"},
    {text: "Grapes", question: "Where are the grapes?", hex: 0x1F347, fileName: "grapes"},
    {text: "A watermelon", question: "Where is the watermelon?", hex: 0x1F349, fileName: "watermelon"},
    {text: "An orange", question: "Where is the orange?", hex: 0x1F34A, fileName: "orange"},
    {text: "A lemon", question: "Where is the lemon?", hex: 0x1F34B, fileName: "lemon"},
    {text: "A banana", question: "Where is the banana?", hex: 0x1F34C, fileName: "banana"},
    {text: "An apple", question: "Where is the apple?", hex: 0x1F34F, fileName: "apple"},
    {text: "A pear", question: "Where is the pear?", hex: 0x1F350, fileName: "pear"},
    {text: "Cherries", question: "Where are the cherries?", hex: 0x1F352, fileName: "cherries"},
    {text: "A strawberry", question: "Where is the strawberry?", hex: 0x1F353, fileName: "strawberry"},
    {text: "A pizza", question: "Where is the pizza?", hex: 0x1F355, fileName: "pizza"},
    {text: "An ice-cream", question: "Where is the ice-cream?", hex: 0x1F366, fileName: "icecream"},
    {text: "A present", question: "Where is the present?", hex: 0x1F381, fileName: "present"},
    {text: "A cake", question: "Where is the cake?", hex: 0x1F382, fileName: "cake"},
    {text: "A pumpkin", question: "Where is the pumpkin?", hex: 0x1F383, fileName: "pumpkin"},
    {text: "A balloon", question: "Where is the balloon?", hex: 0x1F388, fileName: "balloon"},
    {text: "A circus", question: "Where is the circus?", hex: 0x1F3AA, fileName: "circus"},
    {text: "A piano", question: "Where is the piano?", hex: 0x1F3B9, fileName: "piano"},
    {text: "A violin", question: "Where is the violin?", hex: 0x1F3BB, fileName: "violin"},
    {text: "A beach", question: "Where is the beach?", hex: 0x1F3DD, fileName: "beach"},
    {text: "A house", question: "Where is the house?", hex: 0x1F3E0, fileName: "house"},
    {text: "A snake", question: "Where is the snake?", hex: 0x1F40D, fileName: "snake"},
    {text: "A sheep", question: "Where is the sheep?", hex: 0x1F411, fileName: "sheep"},
    {text: "A hen", question: "Where is the hen?", hex: 0x1F413, fileName: "hen"},
    {text: "An octopus", question: "Where is the octopus?", hex: 0x1F419, fileName: "octopus"},
    {text: "An ant", question: "Where is the ant?", hex: 0x1F41C, fileName: "ant"},
    {text: "A bee", question: "Where is the bee?", hex: 0x1F41D, fileName: "bee"},
    {text: "A turtle", question: "Where is the turtle?", hex: 0x1F422, fileName: "turtle"},
    {text: "A chick", question: "Where is the chick?", hex: 0x1F425, fileName: "chick"},
    {text: "A camel", question: "Where is the camel?", hex: 0x1F42A, fileName: "camel"},
    {text: "A dolphin", question: "Where is the dolphin?", hex: 0x1F42C, fileName: "dolphin"},
    {text: "A tiger", question: "Where is the tiger?", hex: 0x1F42F, fileName: "tiger"},
    {text: "A bear", question: "Where is the bear?", hex: 0x1F43B, fileName: "bear"},
    {text: "A squirrel", question: "Where is the squirrel?", hex: 0x1F43F, fileName: "squirrel"},
    {text: "An eye", question: "Where is the eye?", hex: 0x1F441, fileName: "eye"},
    {text: "An ear", question: "Where is the ear?", hex: 0x1F442, fileName: "ear"},
    {text: "A nose", question: "Where is the nose?", hex: 0x1F443, fileName: "nose"},
    {text: "A mouth", question: "Where is the mouth?", hex: 0x1F444, fileName: "mouth"},
    {text: "A hand", question: "Where is the hand?", hex: 0x1F44B, fileName: "hand"},
    {text: "Glasses", question: "Where are the glasses?", hex: 0x1F453, fileName: "glasses"},
    {text: "A t-shirt", question: "Where is the t-shirt?", hex: 0x1F455, fileName: "tshirt"},
    {text: "Trousers", question: "Where are the trousers?", hex: 0x1F456, fileName: "trousers"},
    {text: "A dress", question: "Where is the dress?", hex: 0x1F457, fileName: "dress"},
    {text: "A shoe", question: "Where is the shoe?", hex: 0x1F45E, fileName: "shoe"},
    {text: "A boy", question: "Where is the boy?", hex: 0x1F466, fileName: "boy"},
    {text: "A girl", question: "Where is the girl?", hex: 0x1F467, fileName: "girl"},
    {text: "A book", question: "Where is the book?", hex: 0x1F4D7, fileName: "book"},
    {text: "A phone", question: "Where is the phone?", hex: 0x1F4F1, fileName: "phone"},
    {text: "A fire", question: "Where is the fire?", hex: 0x1F525, fileName: "fire"},
    {text: "A knife", question: "Where is the knife?", hex: 0x1F52A, fileName: "knife"},
    {text: "A spider", question: "Where is the spider?", hex: 0x1F577, fileName: "spider"},
    {text: "A TV", question: "Where is the TV?", hex: 0x1F5A5, fileName: "tv"},
    {text: "A helicopter", question: "Where is the helicopter?", hex: 0x1F681, fileName: "helicopter"},
    {text: "A train", question: "Where is the train?", hex: 0x1F686, fileName: "train"},
    {text: "A bus", question: "Where is the bus?", hex: 0x1F68C, fileName: "bus"},
    {text: "An ambulance", question: "Where is the ambulance?", hex: 0x1F691, fileName: "ambulance"},
    {text: "A taxi", question: "Where is the taxi?", hex: 0x1F695, fileName: "taxi"},
    {text: "A car", question: "Where is the car?", hex: 0x1F697, fileName: "car"},
    {text: "A truck", question: "Where is the truck?", hex: 0x1F69B, fileName: "truck"},
    {text: "A tractor", question: "Where is the tractor?", hex: 0x1F69C, fileName: "tractor"},
    {text: "A salad", question: "Where is the salad?", hex: 0x1F957, fileName: "salad"},
    {text: "An egg", question: "Where is the egg?", hex: 0x1F95A, fileName: "egg"},
    {text: "A kiwi", question: "Where is the kiwi?", hex: 0x1F95D, fileName: "kiwi"},
    {text: "A broccoli", question: "Where is the broccoli?", hex: 0x1F966, fileName: "broccoli"},
    {text: "A crab", question: "Where is the crab?", hex: 0x1F980, fileName: "crab"},
    {text: "A lion", question: "Where is the lion?", hex: 0x1F981, fileName: "lion"},
    {text: "A duck", question: "Where is the duck?", hex: 0x1F986, fileName: "duck"},
    {text: "A bat", question: "Where is the bat?", hex: 0x1F987, fileName: "bat"},
    {text: "A shark", question: "Where is the shark?", hex: 0x1F988, fileName: "shark"},
    {text: "A boat", question: "Where is the boat?", hex: 0x1F6A2, fileName: "boat"},
    {text: "A bike", question: "Where is the bike?", hex: 0x1F6B2, fileName: "bike"},
    {text: "A bed", question: "Where is the bed?", hex: 0x1F6CC, fileName: "bed"},
    {text: "A plane", question: "Where is the plane?", hex: 0x1F6E9, fileName: "plane"},
    {text: "A motorbike", question: "Where is the motorbike?", hex: 0x1F6F5, fileName: "motorbike"},
    {text: "Drums", question: "Where are the drums?", hex: 0x1F941, fileName: "drums"},
    {text: "An avocado", question: "Where is the avocado?", hex: 0x1F951, fileName: "avocado"},
    {text: "A cucumber", question: "Where is the cucumber?", hex: 0x1F952, fileName: "cucumber"},
    {text: "A carrot", question: "Where is the carrot?", hex: 0x1F955, fileName: "carrot"},
    {text: "A heart", question: "Where is the heart?", hex: 0x1F9E1, fileName: "heart"},
    {text: "An owl", question: "Where is the owl?", hex: 0x1F989, fileName: "owl"},
    {text: "A butterfly", question: "Where is the butterfly?", hex: 0x1F98B, fileName: "butterfly"},
    {text: "A gorilla", question: "Where is the gorilla?", hex: 0x1F98D, fileName: "gorilla"},
    {text: "A giraffe", question: "Where is the giraffe?", hex: 0x1F992, fileName: "giraffe"},
    {text: "A zebra", question: "Where is the zebra?", hex: 0x1F993, fileName: "zebra"},
    {text: "A dinosaur", question: "Where is the dinosaur?", hex: 0x1F996, fileName: "dinosaur"},
    {text: "The sun", question: "Where is the sun?", hex: 0x1F31E, fileName: "sun"},
    {text: "The moon", question: "Where is the moon?", hex: 0x1F31B, fileName: "moon"},
    {text: "A star", question: "Where is the star?", hex: 0x1F31F, fileName: "star"},
    {text: "The rain", question: "Where is the rain?", hex: 0x1F327, fileName: "rain"}
];

export const KidsEmoji = (props) => (
    <span role="img" className={props.className} onClick={props.clickHandler} >
        <span>{String.fromCodePoint(eval("KIDS_MAP_"+ props.lang)[props.num].hex)}</span>
    </span>
);

export const KidsLabel = (props) => (
    <span className={props.className}>
        {eval("KIDS_MAP_"+ props.lang)[props.num].text}
    </span>
);

export const KidsQuestion = (props) => (
    <span className={props.className}>
        {eval("KIDS_MAP_"+ props.lang)[props.num].question}
    </span>
);

export function playAudioByItemNumber(itemNumber, lang, audioObject, isQuestion) {
    audioObject.src = audio('./' + lang + "/" + eval("KIDS_MAP_"+ lang)[itemNumber].fileName 
        + (isQuestion ? '_q' : '') + '.mp3');
    audioObject.play().catch(() => {
          // Auto-play was prevented
        });
}